create table if not exists private.iren_objectives (
  objective_id uuid primary key default gen_random_uuid(),
  objective_key text not null unique,
  parent_key text,
  title text not null,
  description text not null default '',
  status text not null default 'FUTURE'
    check (status in ('LOCKED','ACTIVE','BLOCKED','READY','COMPLETE','FUTURE','OBSOLETE')),
  owner_system text not null default 'IREN',
  priority integer not null default 0,
  dependencies jsonb not null default '[]'::jsonb
    check (jsonb_typeof(dependencies) = 'array'),
  success_criteria jsonb not null default '{}'::jsonb
    check (jsonb_typeof(success_criteria) = 'object'),
  protected_action boolean not null default false,
  metadata jsonb not null default '{}'::jsonb
    check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists iren_objectives_status_priority_idx
  on private.iren_objectives (status, priority desc, created_at);

create table if not exists private.iren_jobs (
  job_id uuid primary key default gen_random_uuid(),
  objective_key text references private.iren_objectives(objective_key)
    on update cascade on delete set null,
  title text not null,
  instructions text not null default '',
  owner_system text not null default 'IREN',
  job_type text not null default 'AGENT_WORK',
  status text not null default 'QUEUED'
    check (status in ('QUEUED','RUNNING','WAITING','BLOCKED','NEEDS_APPROVAL','SUCCEEDED','FAILED','CANCELLED')),
  priority integer not null default 0,
  protected_action boolean not null default false,
  requires_human boolean not null default false,
  requested_by text,
  requested_via text not null default 'iren',
  claimed_by text,
  lease_until timestamptz,
  started_at timestamptz,
  completed_at timestamptz,
  result jsonb not null default '{}'::jsonb
    check (jsonb_typeof(result) = 'object'),
  error jsonb not null default '{}'::jsonb
    check (jsonb_typeof(error) = 'object'),
  metadata jsonb not null default '{}'::jsonb
    check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists iren_jobs_status_priority_idx
  on private.iren_jobs (status, priority desc, created_at);
create index if not exists iren_jobs_objective_idx
  on private.iren_jobs (objective_key, created_at desc);

create table if not exists private.iren_commands (
  command_id uuid primary key default gen_random_uuid(),
  command_text text not null,
  source text not null,
  requested_by text,
  status text not null default 'QUEUED'
    check (status in ('QUEUED','PROCESSING','SUCCEEDED','FAILED','CANCELLED')),
  owner text,
  lease_until timestamptz,
  response jsonb not null default '{}'::jsonb
    check (jsonb_typeof(response) = 'object'),
  linked_job_id uuid references private.iren_jobs(job_id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists iren_commands_status_created_idx
  on private.iren_commands (status, created_at);

create table if not exists private.iren_job_events (
  event_id bigint generated by default as identity primary key,
  job_id uuid not null references private.iren_jobs(job_id) on delete cascade,
  event_type text not null,
  event jsonb not null default '{}'::jsonb
    check (jsonb_typeof(event) = 'object'),
  created_at timestamptz not null default now()
);

create index if not exists iren_job_events_job_idx
  on private.iren_job_events (job_id, event_id desc);

alter table private.iren_objectives enable row level security;
alter table private.iren_jobs enable row level security;
alter table private.iren_commands enable row level security;
alter table private.iren_job_events enable row level security;

revoke all on table private.iren_objectives from public, anon, authenticated;
revoke all on table private.iren_jobs from public, anon, authenticated;
revoke all on table private.iren_commands from public, anon, authenticated;
revoke all on table private.iren_job_events from public, anon, authenticated;

insert into private.iren_objectives (
  objective_key, parent_key, title, description, status, owner_system, priority,
  dependencies, success_criteria, protected_action, metadata
) values
(
  'ANEVUM-AUTONOMY', null,
  'Build autonomous ANEVUM operating environment',
  'Create a durable operating system that preserves continuity, determines the next useful action, coordinates subsystem work, records evidence, and keeps ANEVUM moving toward its long-term objectives.',
  'ACTIVE', 'IREN', 100,
  '[]'::jsonb,
  '{"durable_objectives":true,"durable_jobs":true,"command_interface":true,"slack_interface":true,"subsystem_routing":true}'::jsonb,
  false,
  '{"job_type":"AGENT_WORK","canonical":true}'::jsonb
),
(
  'IREN-OBJECTIVE-JOB-ENGINE', 'ANEVUM-AUTONOMY',
  'Deploy IREN objective and job engine',
  'Give IREN durable objectives, commands, jobs, prioritization, protected-action gating, and a continuously running work engine.',
  'ACTIVE', 'IREN', 100,
  '[]'::jsonb,
  '{"schema_deployed":true,"engine_running":true,"status_command":true,"next_command":true,"execute_next_command":true}'::jsonb,
  false,
  '{"job_type":"SOFTWARE_BUILD"}'::jsonb
),
(
  'IREN-COMMAND-SURFACE', 'ANEVUM-AUTONOMY',
  'Make Command the primary IREN terminal',
  'Add a persistent IREN command dock, objective graph, active-job view, decision queue, status summaries, and subsystem navigation to ANEVUM Command.',
  'READY', 'IREN', 95,
  '["IREN-OBJECTIVE-JOB-ENGINE"]'::jsonb,
  '{"command_dock":true,"objective_view":true,"job_view":true,"decision_view":true}'::jsonb,
  false,
  '{"job_type":"SOFTWARE_BUILD"}'::jsonb
),
(
  'IREN-SLACK-INBOUND', 'ANEVUM-AUTONOMY',
  'Connect Slack as IREN operational control',
  'Accept authenticated Slack commands into the same IREN command ledger used by Command and return meaningful completions, failures, blockers, and decisions to Slack.',
  'READY', 'IREN', 94,
  '["IREN-OBJECTIVE-JOB-ENGINE"]'::jsonb,
  '{"signed_ingress":true,"shared_command_ledger":true,"response_delivery":true}'::jsonb,
  false,
  '{"job_type":"SOFTWARE_BUILD"}'::jsonb
),
(
  'GRAEN-INDEPENDENT-RUNTIME', 'ANEVUM-AUTONOMY',
  'Establish GRAEN independent runtime',
  'Make GRAEN independently addressable within the current stack with its own API boundary, research queue, canonical state, artifacts, telemetry, and worker identity.',
  'READY', 'GRAEN', 90,
  '["IREN-OBJECTIVE-JOB-ENGINE"]'::jsonb,
  '{"independent_service":true,"problem_api":true,"research_queue":true,"canonical_artifacts":true}'::jsonb,
  false,
  '{"job_type":"SOFTWARE_BUILD"}'::jsonb
),
(
  'GRAEN-VIABLE-CRYPTO-STRATEGY', 'ANEVUM-AUTONOMY',
  'Find a viable sufficiently active crypto strategy',
  'Research and falsify crypto-native strategy families until one survives frozen development, validation, holdout, cost-stress, delay-robustness, opportunity-frequency, and concentration criteria, or record NO_VIABLE_EDGE_FOUND.',
  'READY', 'GRAEN', 85,
  '["GRAEN-INDEPENDENT-RUNTIME"]'::jsonb,
  '{"development_gate":true,"validation_gate":true,"holdout_gate":true,"cost_stress":true,"sufficient_opportunity_frequency":true}'::jsonb,
  false,
  '{"job_type":"GRAEN_RESEARCH_PROBLEM"}'::jsonb
),
(
  'VELUM-STRATEGY-VALIDATION', 'ANEVUM-AUTONOMY',
  'Verify promoted strategy through VELUM',
  'Replay and parity-test any GRAEN-promoted strategy before RHEN promotion.',
  'READY', 'VELUM', 80,
  '["GRAEN-VIABLE-CRYPTO-STRATEGY"]'::jsonb,
  '{"replay_complete":true,"parity_verified":true}'::jsonb,
  false,
  '{"job_type":"AGENT_WORK"}'::jsonb
),
(
  'RHEN-SHADOW-PROMOTION', 'ANEVUM-AUTONOMY',
  'Promote validated strategy to RHEN shadow',
  'Deploy a VELUM-verified strategy into RHEN shadow operation without granting live execution authority.',
  'READY', 'RHEN', 75,
  '["VELUM-STRATEGY-VALIDATION"]'::jsonb,
  '{"shadow_deployed":true,"evidence_persistent":true}'::jsonb,
  false,
  '{"job_type":"AGENT_WORK"}'::jsonb
)
on conflict (objective_key) do nothing;
